import * as React from "react";
import styled from "styles/styled-components";
import Box from "components/Box";
import { Grid, Typography } from "@material-ui/core";

export interface IHowToPlayProps {
  className?: string;
}

export default (props: IHowToPlayProps) =>  {
  return (
    <StyledContainer>
      <div className="main-panel">
        <div className="main-panel-header">
          <div className="filter-bar">
            <Typography variant="h6">
              How to play
            </Typography>
          </div>
        </div>
        <div className="main-panel-inner">
          What is FootyPredictor?

          Footy predictor is a online football results prediction game where you can win crypto rewards based on your result.

          Who can participate?

          Everybody who have a prepaid access ticket can participate.

          How to buy access ticket and how much it costs?

          Every matchday requires a prepaid access ticket which you need to buy by depositing bitcoins to your account. Price is always B0.0001.

          How to deposit bitcoins?

          Each account have a unique deposit hash which you can find in Deposit section of your account.

          What is a matchday?

          Matchday is a list of 10 highlighted matches usually played on the same weekend throughout major football leagues.

          I bought a access ticket, whats next?

          You need to fill in your predictions for each match of the matchday and submit it. After all the games in the matchday are finished,
          our system calculates the points of each participant and places them accordingly into the standings list. Participants with most points
          get rewards in crypto based on their ranking. Additionally the results are being summed up in seasonal rankings, a season long tournaments
          with a gran pri based on 38 matchdays of a season which is divided between top 3 of the players wit most points throughout the season.

          How do you calculate points?

          From each predicted match of the matchday you can get 0,1,2 or 3 points.
          3 points for guessing correct outcome and score
          2 for correct outcome and correct goal difference
          1 for correct outcome and wrong goal difference
          0 for wrong outcome

          Suppose team A plays team B and you have predicted 1-0 win for team A.

          If the match end with a score A 1-0 B you get 3 points for this match (correct guess of outcome and exact score)
          If the match end with a score A 2-1 B or A 3-2 B you get 2 points for this match (correct guess of outcome and goal difference)
          If the match end with a score A 2-0 B or A 4-1 B you get 1 point for this match (correct guess of outcome, goal difference is not guessed)
          If the match end with a score A 0-0 B or A 1-2 B you get 0 points for this match (outcome guessed wrong)

          What are the rewards?

          The rewards are based on the prize pool of each matchday which is generated by access tickets bought by all participants.
          The prize pool is divided between top 25% of the participants where the highest positioned participant gets the highest reward.



        </div>
      </div>
    </StyledContainer>
  );
}


const StyledContainer = styled(Box)`
`;